general:
  total_threads: 100
  timeout: 60 #in minutes
  results: "{current}/results/[%d-%m-%Y %H-%M-%S]/"
  useragent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"

proxies:
  enabled: True
  threads: 100
  timeout: 10 #in seconds
  use_http: True
  use_socks4: True
  use_socks5: True
  check_http: True
  check_socks4: True
  check_socks5: True

minecraft:
  enabled: True
  timeout: 4 # in seconds
  check_amount: 4 # How many times an account should be used | needs to be 1 or higher
  max_errors_per_try: 3
  account_format: "{email}:{password}:{uuid}"
  outputname: "working_{checkername}_{unix}.txt"

ipvanish:
  enabled: True
  timeout: 5 # in seconds
  max_errors_per_try: 5
  outputname: "working_{checkername}_{unix}.txt"

vyprvpn:
  enabled: True
  timeout: 5 # in seconds
  max_errors_per_try: 5
  outputname: "working_{checkername}_{unix}.txt"
  
nordvpn:
  enabled: True
  timeout: 10 # in seconds
  max_errors_per_try1: 5
  max_errors_per_try2: 5
  outputname: "working_{checkername}_{unix}.txt"

airvpn:
  enabled: True
  timeout: 10 # in seconds
  max_errors_per_try1: 5
  max_errors_per_try2: 5
  outputname: "working_{checkername}_{unix}.txt"

fortnite:
  enabled: True
  timeout: 5 # in seconds
  max_errors_per_try1: 5
  max_errors_per_try2: 3
  user_agent: "Fortnite/++Fortnite+Release-4.5-CL-4166199 Windows/6.2.9200.1.768.64bit"
  authkey: "basic MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE="
  # You should get your own authkey, follow this guide for it -> https://github.com/qlaffont/fortnite-api#init
  outputname: "working_{checkername}_{unix}.txt"